name: foodscan
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # https://github.com/svprdga/Text-Recognition-Flutter/blob/master/pubspec.yaml
  camera: ^0.12.0+2
  google_mlkit_text_recognition: ^0.16.0
  permission_handler: ^12.0.3

  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.15

  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true